using System;
using System.Collections.Generic;
using System.Linq;

namespace CSharp.Quizz.Common
{
    public class QuizzRepository
    {
        private static readonly IReadOnlyCollection<Quizz> QuizzList = new HashSet<Quizz>()
        {
            new("O C# é uma linguagem compilada, tipada e gerenciada, o que isto significa?", Difficulty.EASY, Category.DotNet | Category.ComputerScience),
            new("O que diferencia uma linguagem compilada de uma interpretada?", Difficulty.EASY, Category.ComputerScience),
            new("Explique como o C# funciona", Difficulty.EASY, Category.CSharp),
            new("O que é o CLR?", Difficulty.MEDIUM, Category.DotNet),
            new("O que é IL?", Difficulty.MEDIUM, Category.DotNet),
            new("O que é um Framework?", Difficulty.EASY, Category.ComputerScience),
            new("O que é o .NET?", Difficulty.EASY, Category.DotNet),
            new("O que é o .NET Standard?", Difficulty.EASY, Category.DotNet),
            new("Explique o que é versão semântica", Difficulty.EASY, Category.ComputerScience),
            new("O que significa LTS na versão do software?", Difficulty.EASY, Category.ComputerScience),
            new("O que é um Runtime?", Difficulty.MEDIUM, Category.ComputerScience),
            new("O que é um SDK?", Difficulty.EASY, Category.ComputerScience),
            new("O que é um CLI?", Difficulty.EASY, Category.ComputerScience),
            new("Cite 3 tipos de projetos que temos no .NET", Difficulty.EASY, Category.DotNet),
            new("O que é uma Solution?", Difficulty.EASY, Category.DotNet),
            new("Qual comando para executar uma aplicação .NET?", Difficulty.EASY, Category.DotNet),
            new("Qual comando para compilar uma aplicação .NET?", Difficulty.EASY, Category.DotNet),
            new("Qual comando para publicar uma aplicação .NET?", Difficulty.EASY, Category.DotNet),
            new("Qual nome do método principal de um Console App?", Difficulty.EASY, Category.DotNet),
            new("O que significa Debug?", Difficulty.EASY, Category.ComputerScience),
            new("Como executamos uma aplicação .NET em modo Debug?", Difficulty.EASY, Category.DotNet),
            new("Qual a finalidade da pasta Properties?", Difficulty.EASY, Category.DotNet),
            new("Qual a finalidade das pastas Bin e Obj?", Difficulty.EASY, Category.DotNet),
            new("Quais partes compoem um programa em C#?", Difficulty.EASY, Category.CSharp),
            new("O que são Namespaces?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do using antes dos namespaces?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do using dentro de um método?", Difficulty.EASY, Category.CSharp),
            new("Qual a diferença entre uma variável e uma constante?", Difficulty.EASY, Category.ComputerScience),
            new("Cite 3 nomes reservados que temos no C#", Difficulty.EASY, Category.CSharp),
            new("Quais formas temos de comentar código em C#?", Difficulty.EASY, Category.CSharp),
            new("O que são tipos primitivos?", Difficulty.EASY, Category.ComputerScience),
            new("Qual tipo base no .NET?", Difficulty.EASY, Category.DotNet),
            new("Dado um 'var' de um número real, qual tipo seria o var?", Difficulty.EASY, Category.CSharp),
            new("Dado um 'var' de um número inteiro, qual tipo seria o var?", Difficulty.EASY, Category.CSharp),
            new("Qual a diferença entre char e string?", Difficulty.EASY, Category.ComputerScience),
            new("Qual valor padrão do tipo char?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre 'var' e 'object'?", Difficulty.EASY, Category.ComputerScience),
            new("O que são tipos nulos?", Difficulty.EASY, Category.ComputerScience),
            new("O que são alias? Cite 3 exemplos", Difficulty.MEDIUM, Category.CSharp),
            new("O que são conversões implícitas?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são conversões explícitas?", Difficulty.MEDIUM, Category.CSharp),
            new("Qual a diferença entre 'Parse' e 'Convert'?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são operadores aritméticos e quais temos no C#?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são operadores de atribuição e quais temos no C#?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são operadores de comparação e quais temos no C#?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são operadores lógicos e quais temos no C#?", Difficulty.EASY, Category.CSharp | Category.ProgrammingLogic),
            new("Cite duas estruturas condicionais que temos no C#", Difficulty.EASY, Category.CSharp | Category.ProgrammingLogic),
            new("Cite duas estruturas de repetição que temos no C#", Difficulty.EASY, Category.CSharp | Category.DataStructure),
            new("Qual a diferença entre while e do/while?", Difficulty.EASY, Category.ProgrammingLogic),
            new("Como definimos que um método não retorna valor algum?", Difficulty.EASY, Category.ComputerScience),
            new("Podemos ter métodos sem parâmetros no C#?", Difficulty.EASY, Category.CSharp),
            new("Como tornamos um parâmetro opcional no C#?", Difficulty.MEDIUM, Category.CSharp),
            new("O que são heap e stack?", Difficulty.MEDIUM, Category.ComputerScience),
            new("O que são tipos de valor e tipos de referência?", Difficulty.MEDIUM, Category.ComputerScience),
            new("Onde são armazenados os tipos de valor?", Difficulty.MEDIUM, Category.ComputerScience),
            new("Onde são armazenados os tipos de referência?", Difficulty.MEDIUM, Category.ComputerScience),
            new("O que são Structs?", Difficulty.EASY, Category.ComputerScience),
            new("O que são enumeradores?", Difficulty.EASY, Category.ComputerScience),
            new("O que é um GUID?", Difficulty.EASY, Category.ComputerScience),
            new("O que é interpolação de String?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método CompareTo?", Difficulty.MEDIUM, Category.CSharp),
            new("Qual a finalidade do método Contains?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método StartsWith e EndsWith?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Equals?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método IndexOf e LastIndexOf?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método ToLower e ToUpper?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Insert?", Difficulty.MEDIUM, Category.CSharp),
            new("Qual a finalidade do método Length?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Remove?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Replace?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Split?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Substring?", Difficulty.EASY, Category.CSharp),
            new("Qual a finalidade do método Trim?", Difficulty.EASY, Category.CSharp),
            new("O que é StringBuilder e quando devemos utilizar?", Difficulty.MEDIUM, Category.CSharp),
            new("O que é Regex e quando devemos utilizar?", Difficulty.MEDIUM, Category.ComputerScience),
            new("O que é o DateTime?", Difficulty.EASY, Category.CSharp | Category.DataStructure),
            new("Como obtemos a data de hoje no C#?", Difficulty.EASY, Category.CSharp),
            new("Como convertemos uma data para String?", Difficulty.EASY, Category.CSharp),
            new("Como comparamos duas datas em C#?", Difficulty.MEDIUM, Category.CSharp),
            new("Como podemos obter o ano, mês ou dia no C#?", Difficulty.EASY, Category.ComputerScience),
            new("Como podemos obter o último dia do mês no C#?", Difficulty.EASY, Category.ComputerScience),
            new("Podemos criar datas nulas?", Difficulty.EASY, Category.ComputerScience),
            new("O que são nullable types?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Timezone?", Difficulty.EASY, Category.ComputerScience),
            new("Como obtermos a data sem um Timezone no C#?", Difficulty.EASY, Category.ComputerScience),
            new("O que é DateTime Offset?", Difficulty.EASY, Category.ComputerScience),
            new("O que é um TimeSpan?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do Math.Round, Math.Celling e Math.Floor?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre IEnumerable, IList e ICollection?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre ICollection e IReadOnlyCollection?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre IEnumerable e IEqueryable?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre List e IList?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre HashSet e List?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre List e LinkedList?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Add e AddRange em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Clear em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Contains em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método CopyTo em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Exists em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Find e FindAll em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método IndexOf e LastIndexOf em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método FindIndex, FindLast e FindLastIndex em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Insert e InsertRange em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Remove, RemoveAll, RemoveAt e RemoveRange em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Reverse em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Sort em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método ForEach em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Where em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Select em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método SelectMany em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do método Cast em uma lista?", Difficulty.EASY, Category.ComputerScience),
            new("O que significa FIFO e LIFO?", Difficulty.EASY, Category.ComputerScience),
            new("Cite uma estrutura de dados que implementa LIFO", Difficulty.EASY, Category.ComputerScience),
            new("Cite uma estrutura de dados que implementa FIFO", Difficulty.EASY, Category.ComputerScience),
            new("O que são Classes e Objetos?", Difficulty.EASY, Category.ComputerScience),
            new("O que é uma instância?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Propriedades?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Métodos construtores?", Difficulty.EASY, Category.ComputerScience),
            new("O que é o Garbage Collector?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Object Dispose?", Difficulty.EASY, Category.ComputerScience),
            new("Defina os modificadores public, private e protected", Difficulty.EASY, Category.ComputerScience),
            new("O que são objetos estáticos?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Herança?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Upcast e Downcast?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Interfaces?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Classes abstratas?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade das Classes seladas?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Sobrecarga de métodos?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Sobrescrita de método?", Difficulty.EASY, Category.ComputerScience),
            new("Como podemos Comparar dois objetos no C#?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do Dispose?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Encapsulamento?", Difficulty.EASY, Category.ComputerScience),
            new("O que é Polimorfismo?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Tipos complexos?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Delegates?", Difficulty.EASY, Category.ComputerScience),
            new("O que são events?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre Events e Delegates?", Difficulty.EASY, Category.ComputerScience),
            new("O que são os generics?", Difficulty.EASY, Category.ComputerScience),
            new("Como restringimos um tipo genérico?", Difficulty.EASY, Category.ComputerScience),
            new("Como tratamos erros no C#?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a finalidade do finally?", Difficulty.EASY, Category.ComputerScience),
            new("Para que serve o Try/Parse?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Tasks?", Difficulty.EASY, Category.ComputerScience),
            new("Para que serve async/await?", Difficulty.EASY, Category.ComputerScience),
            new("Qual a diferença entre Task.FromResult e o uso de await?", Difficulty.EASY, Category.ComputerScience),
            new("Para que usamos a interface IEquatable?", Difficulty.EASY, Category.ComputerScience),
            new("Para que usamos a interface IComparable?", Difficulty.EASY, Category.ComputerScience),
            new("Quando utilizamos a interface IDisposable?", Difficulty.EASY, Category.ComputerScience),
            new("O que são Extension methods?", Difficulty.EASY, Category.ComputerScience)
        };

        public List<Quizz> RandomizeQuizz()
        {
            return QuizzList.OrderBy(a => Guid.NewGuid()).Take(10).ToList();
        }
    }
}
